FROM rocker/r-ver:4.4.1
ARG WHEN
RUN mkdir /home/analysis
RUN R -e "options(repos = \
  list(CRAN = 'http://mran.revolutionanalytics.com/snapshot/2019-01-06/')); \
  install.packages('tidystringdist')"
COPY index.Rmd /home/analysis/index.Rmd 
CMD R -e "source('/home/analysis/index.Rmd')"